### ISSUE TITLE
Prepare blackfire integration

### ISSUE THREAD

**Issue by StaffNowa** [StaffNowa/docker-symfony#19]
docker-compose.yml
```
version: '3'

services:
  blackfire:
    image: blackfire/blackfire
    ports: ["8707"]
    environment:
      # Exposes BLACKFIRE_SERVER_* environment variables from the host
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN

```
PHP installation

```
RUN curl -sS https://packages.blackfire.io/gpg.key | apt-key add - && \
    echo "deb http://packages.blackfire.io/debian any main" | tee /etc/apt/sources.list.d/blackfire.list && \
    apt-get update && apt-get install -y blackfire-agent blackfire-php
```

.env configuration

```
# Blackfire
BLACKFIRE_SERVER_ID=
BLACKFIRE_SERVER_TOKEN=
BLACKFIRE_CLIENT_ID=
BLACKFIRE_CLIENT_TOKEN=
```
