### ISSUE TITLE
PWA does not work on external_network = off

### ISSUE THREAD

**Issue by StaffNowa** [StaffNowa/docker-symfony#35]
Quick fix:
```
    networks:
      default:
        aliases:
          - ${PROJECT_DOMAIN_1}
```
